module Utilities

using Optim, Interpolations
using GeneralizedSchrodingerResearch.AnalyticalSolutions: NSE_3_5_soliton, precompile_NSE_3_5_7_soliton, NSE_3_5_7_soliton
using GeneralizedSchrodingerResearch.BaseUtilities: M0_M1_to_ε2_ε3, find_threshold, shift_pulse_to_center, relative_error_to_amplitude

include("construct_approximate_solutions.jl")
export construct_approximate_NSE_3_5_solution, construct_approximate_NSE_3_5_7_solution, construct_best_approximate_NSE_3_5_7_solution

end